version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fp-matsuri-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: staff_db
      MYSQL_USER: staff_user
      MYSQL_PASSWORD: staff_password
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  localstack:
    image: localstack/localstack:latest
    container_name: fp-matsuri-localstack
    platform: linux/amd64
    environment:
      - SERVICES=sns,sqs
      - DEBUG=0
      - DEFAULT_REGION=ap-northeast-1
      - MAIN_CONTAINER_NAME=fp-matsuri-localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: